#!/usr/bin/env python3
"""Generate the Phaser calibration module from the office asset manifest."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "assets/office/manifests/office-assets.json"
OUTPUT = ROOT / "frontend/src/scene/furniture/generated-calibrations.ts"


def calibration_data(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for asset in manifest.get("assets", []):
        runtime = asset.get("runtime")
        if not runtime:
            continue
        asset_id = asset.get("variantOf") or asset["id"]
        orientation = asset.get("orientation", "north_east")
        result.setdefault(asset_id, {})[orientation] = runtime
    return result


def write_catalog(manifest: dict[str, Any], output: Path = OUTPUT) -> None:
    contents = "// Generated by scripts/generate_office_asset_calibrations.py. Do not edit.\n" + f"export const GENERATED_FURNITURE_CALIBRATIONS = {json.dumps(calibration_data(manifest), ensure_ascii=False, indent=2)} as const;\n"
    output.write_text(contents)


def main() -> None:
    write_catalog(json.loads(MANIFEST.read_text()))
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
